import type { Metadata } from "next";
import ThemeMiuProvider from '@/providers/ThemeMui'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeMiuProvider>{children}</ThemeMiuProvider>
      </body>
    </html>
  );
}
